version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ID=
      - CLIENT_SECRET=
      - CLIENT_URL="http://localhost:3000/"
      - REDIRECT_URL="http://localhost:8080/"
    depends_on:
      - elasticsearch

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL="http://localhost:8080"
